### ISSUE TITLE
How to add validation dynamically?

### ISSUE THREAD

**Issue by jayjhaveri** [NaingAungLuu/form-conductor#34]
Suppose the user selects US citizen: yes, then I want to mandatory some fields; how can I do this with the library?

**Comment by NaingAungLuu** [comment]
Hello @jayjhaveri ,
Such validation isn't available using `form-conductor` as of now. However, I'm already working on a solution for `ConditionalMandatory` rules for such scenarios where we dynamically evaluate `isOptional` value based on form state. Please stay tuned!

**Comment by jayjhaveri** [comment]
Hey @NaingAungLuu , thank you so much for your response. Great library, by the way. Keep it up.

**Comment by NaingAungLuu** [comment]
Hey @jayjhaveri!
It's my pleasure to inform you that the feature you've requested is now available using `@DynamicOptional` annotation in version `0.4.0` 🚀
Documentations are on the way too!
Please use the following artifacts:
```kotlin
val formConductorVersion = "0.4.0"
implementation("me.naingaungluu.formconductor:core:$formConductorVersion")
implementation("me.naingaungluu.formconductor:compose-ui:$formConductorVersion")
```

**Comment by jayjhaveri** [comment]
Hey @NaingAungLuu, that's amazing. Thanks for notifying me, and eagerly waiting for your documentation.
